version: '3.1'

services:
  review-microservice-container:
    image: jayoswal20/review-microservice:1.1.0
    container_name: review-microservice-container
    ports:
      - "8083:8083"
    networks:
      - app-network-external
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  company-microservice-container:
    image: jayoswal20/company-microservice:1.1.0
    container_name: company-microservice-container
    ports:
      - "8081:8081"
    networks:
      - app-network-external
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - review-microservice-container
  job-microservice-container:
    image: jayoswal20/job-microservice:1.2.0
    container_name: job-microservice-container
    ports:
      - "8082:8082"
    networks:
      - app-network-external
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - company-microservice-container
  api-gateway-container:
    image: jayoswal20/api-gateway:1.0.0
    container_name: api-gateway-container
    ports:
      - "8084:8084"
    networks:
      - app-network-external
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - job-microservice-container

networks:
  app-network-external:
    external: true

